---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxsrv
  name: influxsrv
  namespace: hyperpilot
spec:
  ports:
  - name: port-1
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: port-2
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: port-3
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: influxsrv
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: influxsrv
  name: influxsrv
  namespace: hyperpilot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxsrv
    spec:
      hostname: influxsrv
      volumes:
      - hostPath:
          path: /home/monitoring/influx_data
        name: influx-data
      containers:
      - env:
        - name: ADMIN_USER
          value: root
        - name: PRE_CREATE_DB
          value: prometheus
        - name: INFLUXDB_INIT_PWD
          value: default
        image: jpra1113/influx:remote_storage_adapter
        name: influxsrv
        ports:
        - containerPort: 8083
          hostPort: 8083
          protocol: TCP
        - containerPort: 8086
          hostPort: 8086
          protocol: TCP
        - containerPort: 8088
          hostPort: 8088
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influx-data
        resources:
          requests:
            cpu: 0.2
            memory: 300Mi